### ISSUE TITLE
请教一下部署问题

### ISSUE THREAD

**Issue by rieval** [h404bi/www.h404bi.com#125]
我是从 Topics 上搜索 Saber 后发现这个项目的

一开始我以为这是一个 Saber Theme，但之后立马发现并不是这样

然后我突然困惑了，我该如何使用该项目的 Saber Theme ？

如果我 Fork 或者 Clone 了这个项目，我该如何保证在填充自己的内容(文章，站点信息等)的同时使该项目的其他内容(主题配置等)和上游保持同步呢？合并上游不会产生很大冲突吗？

请赐教，谢谢

**Comment by h404bi** [comment]
我博客的主题不再单独分离出来了，你想用的话直接拷贝theme目录（MIT协议）到你的 saber 项目里调用吧。如果你想保持跟我的主题同步，自行留意并手动更新覆盖新文件。

**Comment by rieval** [comment]
感谢解惑

;-)
