### ISSUE TITLE
[ga-lite] wrong information caught on navigate to another page

### ISSUE THREAD

**Issue by NeverBehave** [h404bi/www.h404bi.com#147]
https://github.com/h404bi/www.h404bi.com/blob/cf38eb8c71bb21f67f03bfed12f3c4963b2a653a/packages/saber-plugin-ga-lite/saber-browser.js#L21

When the route loaded, the page info (e.g. title) have not yet changed, and ga-lite has already tried to fetch page information at that moment, which will catch last page's information. 

Here is an example when I navigate from index to one of the blog: the document title is still from the previous page.
 
![Screenshot_20200522_214209](https://user-images.githubusercontent.com/17120571/82719054-196e7f00-9c75-11ea-91cb-f13e599b8dba.png)

**Comment by h404bi** [comment]
I didn't notice the issue and thanks for reporting it. I did some research and found it's a backlog issue of [vue-router](https://github.com/vuejs/vue-router/issues/1968), which may have affected all other similar modules. 

`Vue.nextTick` does not work and using `setTimout` seems ok but it's not the best choice.

**Comment by h404bi** [comment]
> `Vue.nextTick` does not work and using `setTimout` seems ok but it's not the best choice.

Using `setTimout` can cause duplicate requests when accessing the site for the first time.

![20200523111740](https://user-images.githubusercontent.com/5764917/82720568-3e9bd580-9ce7-11ea-99b7-fa7f9f1786aa.png)

**Comment by NeverBehave** [comment]
> > `Vue.nextTick` does not work and using `setTimout` seems ok but it's not the best choice.
> 
> Using `setTimout` can cause duplicate requests when accessing the site for the first time.
> 
> ![20200523111740](https://user-images.githubusercontent.com/5764917/82720568-3e9bd580-9ce7-11ea-99b7-fa7f9f1786aa.png)

Hummm, could you try setting a flag e.g. `console.log('triggered')` at the same time?

I have tested locally it works fine, probably some theme related stuff?

**Comment by h404bi** [comment]
It's probably caused by my local apache server, it's gone after I switch to nginx.
