### ISSUE TITLE
Feed: Restore the src of lazy loaded images

### ISSUE THREAD

**Issue by h404bi** [h404bi/www.h404bi.com#30]
**Current method**: Using [markdown-it-lazy-image](https://github.com/h404bi/markdown-it-lazy-image) to replace all images' `src` attribute to `data-src` attribute, then replace `src` with a placeholder. Finally loading those images when articles loads.

**The problem**: Actually it changes the article's content. The modified content spread through the RSS, and make RSS readers unhappy. Subscribers couldn't see all the images of the article since RSS readers don't have a lazyload feature.

![20190520232619](https://user-images.githubusercontent.com/5764917/58033230-b3798400-7b56-11e9-99b4-096199e022ea.png)

**Comment by kidonng** [comment]
Maybe we can use `src` in SSR and `data-src` in browser, and let the feed plugin resolve SSR pages instead.

**Comment by h404bi** [comment]
It's hard to do this I guess. `saber-plugin-image` was considered to be the alternative, but I don't like the design of that plugin.
