### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [h404bi/www.h404bi.com#83]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`2015-09-20-new-mac-env-bootstrap.md`](https://github.com/h404bi/www.h404bi.com/blob/4c450317f36e652f284a0300e4d5ca2ebf160cf1/pages/_posts/2015-09-20-new-mac-env-bootstrap.md). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by h404bi** [comment]
Thanks, I updated it to the GitHub repository URL.
